# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  extract_kernel:
    desc: The boot generator is used to extract the kernel image for a Debian package.
    vars:
      result_folder: '{{.result_folder | default "./build/"}}'
      base_spec: '{{.base_spec | default "base.yaml"}}'
      boot_spec: '{{.boot_spec | default "boot.yaml"}}'
      kernel: '{{.kernel | default "vmlinuz"}}'
    cmds:
      - mkdir -p {{.result_folder}}
      - set -o pipefail && boot_generator {{.boot_spec}} {{.result_folder}} 2>&1 | tee {{.result_folder}}{{.kernel}}.log
      - mv {{.result_folder}}{{.kernel}}-* {{.result_folder}}{{.kernel}} || true
    preconditions:
      - test -f {{.boot_spec}}
    sources:
      - '{{.base_spec}}'
      - '{{.boot_spec}}'
    generates:
      - '{{.result_folder}}{{.kernel}}'
