# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  build_qemu:
    desc: Use embdgen to build the QEMU disc image
    vars:
      result_folder: '{{.result_folder | default "./build/"}}'
      partition_layout: '{{.partition_layout | default "image.yaml"}}'
      disc_image: '{{.disc_image | default "image.raw"}}'
      root_tarball: '{{.root_tarball | default "root.config.tar"}}'
    cmds: 
      - mkdir -p  {{.result_folder}}
      - set -o pipefail && embdgen -o {{.result_folder}}{{.disc_image}} {{.partition_layout}} 2>&1 | tee {{.result_folder}}{{.disc_image}}.log
    preconditions: 
       - test -f {{.partition_layout}}
       - test -f {{.result_folder}}{{.root_tarball}}
    sources: 
       - '{{.partition_layout}}'
    generates: 
       - '{{.result_folder}}{{.disc_image}}'
