# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  build:
    desc: The initrd image is build using the initrd generator.
    vars:
      result_folder: '{{.result_folder | default "./build/"}}'
      base_spec: '{{.base_spec | default "base.yaml"}}'
      initrd_spec: '{{.initrd_spec | default "initrd.yaml"}}'
      initrd_img: '{{.initrd_img | default "initrd.img"}}'
    cmds:
      - mkdir -p {{.result_folder}}
      - set -o pipefail && initrd_generator {{.initrd_spec}} {{.result_folder}} 2>&1 | tee {{.result_folder}}{{.initrd_img}}.log
    sources:
      - '{{.base_spec}}'
      - '{{.initrd_spec}}'
    generates:
      - '{{.result_folder}}{{.initrd_img}}'
