# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  build:
   desc: The root generator is used to build a sysroot variant of the root filesystem.
   vars:
      result_folder: '{{.result_folder | default "./build/"}}'
      base_spec: '{{.base_spec | default "base.yaml"}}'
      root_spec: '{{.root_spec | default "root.yaml"}}'
      sysroot: '{{.sysroot | default "root_sysroot.tar"}}'
   cmds: 
      - mkdir -p {{.result_folder}}
      - set -o pipefail && root_generator --sysroot --no-config {{.root_spec}} {{.result_folder}} 2>&1 | tee {{.result_folder}}{{.sysroot}}.log
   preconditions: 
      - test -f {{.root_spec}}
   sources:
      - '{{.base_spec}}'
      - '{{.root_spec}}'
   generates: 
      - '{{.result_folder}}{{.sysroot}}'

  install:
   desc: Install sysroot_tarball to workspace
   vars:
      result_folder: '{{.result_folder | default "./build/"}}'
      sysroot: '{{.sysroot | default "root_sysroot.tar"}}'
      sysroot_location: '{{.sysroot_location | default "/workspace/sysroot_"}}'
      arch: '{{.arch | default "aarch64"}}'
   cmds: 
      - task: build
      - rm -rf {{.sysroot_location}}{{.arch}}/*
      - tar xf {{.result_folder}}{{.sysroot}} -C {{.sysroot_location}}{{.arch}}/ || true
   preconditions:
      - test -f {{.result_folder}}{{.sysroot}}
   method: none
