#!/bin/bash

set -e

if [ ! -f "/build/project_source" ]; then
    echo "No project selected!"
    echo "Please run project_open first."
    exit 1
fi

export IMAGE=$(cat /build/project_source)
export RESULT_FOLDER=$(cat /build/project_result)
export PROJECT="${RESULT_FOLDER}/elbe.prj"

if [ ! -f "$PROJECT" ]; then
    echo "Project invalid, no project ID found!"
    echo "Please run project_open first."
    exit 1
fi 

export PROJECT_ID=$(cat ${PROJECT})

if [ -z "$PROJECT_ID" ]; then
    echo "Invalid project ID!"
    echo "Please run project_open first."
    exit 1
fi

elbe control list_projects | grep $PROJECT_ID
if [ $? -ne 0 ]; then
    echo "Project doesn't exist!"
    echo "Please run project_open first."
    exit 1
fi
