#!/bin/bash

set -e

APP_FOLDER=$1

if [ ! -d $APP_FOLDER ]; then
    echo "Please provide the app folder."
    exit 1
fi

if [ ! -f "$APP_FOLDER/CMakeLists.txt" ]; then
    echo "The app seems to be no cmake app."
    exit 1
fi

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

IMAGE_NAME=$(basename $IMAGE)
INSTALL_FOLDER="/build/sdks/${IMAGE_NAME}"

ENV=$(find ${INSTALL_FOLDER} -name "environment-setup-elbe*")
source "$ENV"

APP_NAME=$(basename ${APP_FOLDER})
BUILD_FOLDER="/build/results/apps/${APP_NAME}"
rm -rf "$BUILD_FOLDER"
mkdir -p "$BUILD_FOLDER"

cmake -B "${BUILD_FOLDER}" -S "${APP_FOLDER}"

cd "$BUILD_FOLDER"

make
