#!/bin/bash

port=7587

sudo lsof -i :$port > /dev/null
if [ $? -eq 0 ]; then
    echo "Elbe port is already in use."
    exit 0
else
    # use python packages from host env in parallel
    sudo bash -c "source /build/venv/bin/activate; PYTHONPATH=/usr/lib/python3/dist-packages:$PYTHONPATH elbe daemon --port=$port --soap > /tmp/elbe_service.log 2>&1" &
    echo "Elbe service started."
fi
