#!/bin/bash

# Used feature layers.
LAYERS="base pbuilder rust kiwi"
# Container version
VERSION="testing"

BASE_NAME="sdk"
REPO="linux.elektrobit.com/ebcl"
BASE_CONTAINER_NAME="ubuntu:22.04"

if [ -z $BUILDER ]; then
    # docker or buildah
    BUILDER="docker"
fi

echo "BUILDER: ${BUILDER}"

function build_container() {
    $BUILDER build \
        -t ${CONTAINER_NAME} \
        --build-arg BASE_CONTAINER_NAME="${BASE_CONTAINER_NAME}" \
        ${FOLDER}
}

export BASE_CONTAINER_NAME

for FOLDER in $LAYERS; do
    CONTAINER_NAME="${REPO}/${BASE_NAME}_${FOLDER}:${VERSION}"
    build_container
    BASE_CONTAINER_NAME="$REPO/${BASE_NAME}_${FOLDER}:${VERSION}"
done

$BUILDER tag ${BASE_CONTAINER_NAME} "${REPO}/${BASE_NAME}:${VERSION}"
