#!/bin/bash

VERSION="testing"

if [ -z $RUNNER ]; then
    # docker or podman
    RUNNER="docker"
fi

echo "RUNNER: ${RUNNER}"

SCRIPT=$(realpath "${BASH_SOURCE[0]}")
SCRIPT_DIR=$(dirname $SCRIPT)
echo "SCRIPT FOLDER: ${SCRIPT_DIR}"

# find workspace folder
WORKSPACE=$(realpath "$SCRIPT_DIR/..")
echo "WORKSPACE: $WORKSPACE"

# find images folder
IMAGES=$(realpath "$SCRIPT_DIR/../images")
echo "IMAGES: $IMAGES"

# find identity folder
IDENTITY=$(realpath "$SCRIPT_DIR/../identity")
echo "IDENTITY: $IDENTITY"

# find results folder
mkdir -p /tmp/results/{images,packages} || true
RESULTS_DIR=$(realpath "$SCRIPT_DIR/../results")
echo "RESULT FOLDER: $RESULTS_DIR"
RESULTS_IMAGES_DIR=$(realpath "$RESULTS_DIR/images")
RESULTS_PACKAGES_DIR=$(realpath "$RESULTS_DIR/packages")


if [ ! -z "$@" ]; then
    $RUNNER run --rm \
        --name ebcl_sdk \
        -e "CI_COMMAND=$@" \
        -v ${HOME}/.ssh:/home/dev/.ssh:ro \
        -v ${RESULTS_IMAGES_DIR}:/build/results/images:rw \
        -v ${RESULTS_PACKAGES_DIR}:/build/results/packages:rw \
        -v ${WORKSPACE}:/workspace:rw \
        -v ${IMAGES}:/build/images:ro \
        -v ${IDENTITY}:/build/identity:ro \
        --privileged \
        linux.elektrobit.com/ebcl/sdk:testing
else
    $RUNNER run --rm -it \
        --name ebcl_sdk \
        -v ${HOME}/.ssh:/home/dev/.ssh:ro \
        -v ${RESULTS_IMAGES_DIR}:/build/results/images:rw \
        -v ${RESULTS_PACKAGES_DIR}:/build/results/packages:rw \
        -v ${WORKSPACE}:/workspace:rw \
        -v ${IMAGES}:/build/images:ro \
        -v ${IDENTITY}:/build/identity:ro \
        --privileged \
        linux.elektrobit.com/ebcl/sdk:testing
fi
