version: '3'

vars:
  arch: 'aarch64'
  partition_layout: ../image.yaml
  root_filesystem_spec: root.yaml
  result_folder: ./build
  disc_image: ./build/image.raw
  base_tarball: build/ebcl_pi4.tar
  root_tarball: build/ebcl_pi4.config.tar
  sysroot_tarball: build/ebcl_pi4_sysroot.tar

includes:
  rpi:
    taskfile: ../../raspberry.yml
    flatten: true

tasks:
  default:
    desc: Build raspberry pi 4 image
    cmds:
      - task: build_root_base
      - task: build_rootfs
      - task: build_image
