#!/bin/bash

# This script is exectued in the container environment,
# after the VS Code dev-container build.

clone_repos() {
    local repo_type=$1
    local repo_list=$2
    local target_dir=$3

    if [ ! -z "$repo_list" ]; then
        echo "Cloning ${repo_type} repos..."
        mkdir -p $target_dir
        cd $target_dir
        IFS=","
        for repo in $repo_list
        do
            git clone $repo
        done
        cd -
    fi
}

echo "EBcL template ${WS_VERSION}"
echo "Setting EBcL container up..."


# Move SSH keys
if [ -d "tools/.ssh" ]; then
    echo "SSH keys found."

    if [ ! -d "~/.ssh" ]; then
        mkdir -p ~/.ssh
    fi

    echo "Moving ssh keys to ~/.ssh"
    rm -rf ~/.ssh/*
    mv tools/.ssh/* ~/.ssh/

    echo "Deleting copied SSH keys from tools."
    rm -rf tools/.ssh
else
    echo "No SSH keys found."
fi

# Setup /build folder
echo "Linking workspace to build folder..."
for folder in results/images results/packages results/apps images identity sysroot_x86_64 sysroot_aarch64
do
    sudo rm -rf /build/${folder}
    sudo ln -s /workspace/${folder} /build/${folder}
done

# source user env, if it exists
ENV="tools/user_config/.env"
if [ -f "$ENV" ]; then
    echo "Sourcing '${ENV}'..."    
    source $ENV
fi

# Run user setup
if [ -d "/workspace/tools/user_config" ]; then
    echo "Running user setup..."
    if [ -f "/workspace/tools/user_config/settings.json" ]; then
        echo "Overwriting VS Code settings..."
        rm -f /workspace/.vscode/settings.json
        cp /workspace/tools/user_config/settings.json /workspace/.vscode/settings.json
    fi
else
    echo "No user config found. You can provide your own init scripts in ~/.ebcl_config"
fi

# Link tools to tools folder
mkdir -p /workspace/tools
for tool in embdgen ebcl_build_tools ebcl_vscode_tools
do
    if [ ! -L /workspace/tools/${tool} ]; then
        echo "Symlinking ${tool} as tools/${tool}..."
        ln -s /build/${tool} /workspace/tools/${tool}
    fi
done

# Clone user apps
clone_repos "user apps" "$USER_APP_REPO" "/workspace/apps/user"

# Clone user images
clone_repos "user images" "$USER_IMAGE_REPO" "/workspace/images/user"

# Generate VS Code build tasks
generate_build_tasks

# Workaround for robot tests
sudo bash -c 'echo "/workspace/robot_tests/lib" > /build/venv/lib/python3.10/site-packages/_Fakeroot.pth' || true
