#!/bin/bash

# This script is exectued in the host environment,
# before the VS Code dev-container build.

CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "ghcr.io" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')

echo "Setting EBcL workspace up..."
echo "Using EBcL container ${CONTAINER_TAG}."

# Create tools folder
mkdir -p tools

# Create cache folders
mkdir -p state/cache
mkdir -p state/apt

source .env

# Copy user config
if [ -d "${HOME}/.ebcl_config" ]; then
    echo "Copying user config..."
    rm -rf tools/user_config
    mkdir -p tools/user_config
    cp -R ~/.ebcl_config/* tools/user_config
    cp -R ~/.ebcl_config/.env tools/user_config
else
    echo "No user config found. You can provide your own init scripts in ~/.ebcl_config"
fi

# source user env, if it exists
ENV="tools/user_config/.env"
if [ -f "$ENV" ]; then
    echo "Sourcing '${ENV}'..."    
    source $ENV
fi

# Copy SSH keys
if [ ${COPY_SSH} -eq 1 ]; then
    echo "Copying SSH keys from host..."
    if [ -d ${HOME}/.ssh ]; then
        echo "Copying SSH folder to tools..."
        rm -rf tools/.ssh
        mkdir -p tools/.ssh
        cp -R ${HOME}/.ssh/* tools/.ssh/
        echo "Copied keys:"
        ls -lah tools/.ssh/*
    else
        echo "No .ssh folder found!"
    fi
else
    echo "Not copying SSH keys from host."
fi

echo ""
echo "---------------------------------------------------------------------------"
echo "Checking required tools on the development host"
echo "---------------------------------------------------------------------------"

check_package() {
    if dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed"; then
        echo "Required package $1 is installed."
    else
        echo "Error: $1 is not installed."
        echo "Please install it using 'sudo apt install $1'."
        return 1
    fi
}

required_packages=("python3" "python3-venv" "python-is-python3" "binfmt-support" "qemu-user-static")
all_packages_installed=true

echo "Checking packages..."
for package in "${required_packages[@]}"; do
    if ! check_package "$package"; then
        all_packages_installed=false
    fi
done

if [ "$all_packages_installed" = true ]; then
    echo "Finished checking the host environment. You are good to go!"
else
    echo "Some required packages are missing. Please install them and try again."
    echo "Please double check the recommended setup in https://elektrobit.github.io/ebcl_template/intro/setup.html"
    exit 1
fi
echo "---------------------------------------------------------------------------"
