#!/bin/bash

set -e

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

PACKAGE=$(realpath $1)

if [ ! -f $PACKAGE ]; then
    echo "File $PACKAGE not found!"
    exit 1
fi

elbe prjrepo upload_pkg $PROJECT_ID $PACKAGE
