#!/bin/bash

set -e

IMAGE=$(realpath $1)
IMAGE_NAME=$(basename $IMAGE)
RESULT_FOLDER="/build/results/images/${IMAGE_NAME:0:-4}"
PROJECT="${RESULT_FOLDER}/elbe.prj"

mkdir -p $RESULT_FOLDER

CREATE_PROJECT=1
if [ -f ${PROJECT} ]; then
    PROJECT_ID=$(cat ${PROJECT})
    if [ -n "${PROJECT_ID}" ]; then
        elbe control list_projects | grep "$PROJECT_ID"
        if [ $? -eq 0 ]; then
            echo "Project exists. Reusing ${PROJECT_ID}."
            CREATE_PROJECT=0
        fi
    fi
fi 

if [ ${CREATE_PROJECT} -eq 1 ]; then
    # create new elbe project
    echo "Creating new elbe project."
    elbe control create_project > $PROJECT
fi

echo "Project file: $PROJECT"
PROJECT_ID=$(cat ${PROJECT})
echo "Project ID: ${PROJECT_ID}"

# link project as active project
echo $RESULT_FOLDER > /build/project_result
echo $IMAGE > /build/project_source

# set XML to avoid errors in follow up commands.
PRE_XML="${RESULT_FOLDER}/${IMAGE_NAME}.gz"
elbe preprocess --output=${PRE_XML} $IMAGE
elbe control set_xml ${PROJECT_ID} ${PRE_XML}

project_show
