#!/bin/bash

set -e

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

SDK_INSTALLER="${RESULT_FOLDER}/setup-elbe-sdk-aarch64-linux-gnu-aarch64-1.0.sh"
SDK_INSTALLER=$(realpath $SDK_INSTALLER)

echo "SDK installer: ${SDK_INSTALLER}"

if [ ! -f ${SDK_INSTALLER} ]; then
    echo "SDK installer not found."
    echo "Please build the SDK with project_build_sdk."
    exit 1
fi

chmod +x $SDK_INSTALLER

IMAGE_NAME=$(basename $IMAGE)
INSTALL_FOLDER="/build/sdks/${IMAGE_NAME}"

mkdir -p ${INSTALL_FOLDER}

$SDK_INSTALLER -y -d "${INSTALL_FOLDER}"
