#!/bin/bash

set -e

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

IMAGE_NAME=$(basename $IMAGE)
PRE_XML="${RESULT_FOLDER}/${IMAGE_NAME}.gz"

echo "Preprocessing $IMAGE as ${PRE_XML}."
elbe preprocess --output=${PRE_XML} $@ $IMAGE
elbe control set_xml ${PROJECT_ID} ${PRE_XML}
elbe control build ${PROJECT_ID}
