#!/bin/bash

set -e

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

echo "Project info:"
echo "Image: ${IMAGE}"
echo "Result folder: ${RESULT_FOLDER}"
echo "Elbe project ID: ${PROJECT_ID}"
echo "Project initvm status:"

elbe control list_projects | grep ${PROJECT_ID}
