#!/bin/bash

source project_env
if [ $? -ne 0 ]; then
    exit 1
fi

elbe control get_files --output ${RESULT_FOLDER} ${PROJECT_ID}

set +e
ERROR=$(cat "${RESULT_FOLDER}/log.txt" | grep "\[ERROR\]")
if [ $? -eq 0 ]; then 
    echo "ERROR: Build failed, see log.txt!"
    cat "${RESULT_FOLDER}/log.txt" | grep "\[ERROR\]"
else
    echo "SUCCESS: Build was successful!"
fi

echo "The build result was written to ${RESULT_FOLDER}."
