#!/bin/bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}"
echo "Current directory: $PWD"

if [[ ! -d ../.venv ]]; then
    echo "Preparing venv for container build tool..."
    cd ..
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r tools/requirements.txt
    cd container
fi

echo "Building EBcL SDK dev container..."
python3 build_container.py
