version: '3'

vars:
  arch: 'aarch64'
  partition_layout: ../image.yaml
  root_filesystem_spec: root.yaml
  initrd_spec: ../initrd.yaml
  boot_spec: ../boot.yaml
  config_root: config_root.sh
  base_tarball: build/ebcl.tar
  root_tarball: build/ebcl.config.tar
  sysroot_tarball: build/ebcl_sysroot.tar
  qemu_net_append: ",ipv6-net=fd00::eb/64,ipv6-host=fd00::eb:1,ipv6-dns=fd00::eb:3,hostfwd=tcp::2222-:22,hostfwd=tcp::3333-:3333"
  kernel_cmdline_append: "rw"


includes:
  qemu_aarch64:
    taskfile: ../../../../qemu_aarch64.yml
    flatten: true
  qemu:
    taskfile: ../../../../qemu.yml
    flatten: true

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:   
      - task: build_boot
      - task: build_root_base
      - task: build_rootfs
      - task: build_initrd
      - task: build_image
      - task: run_qemu_internal
  ssh:
    desc: Connect to the running qemu instance via ssh
    cmds:
      - ssh-keygen -f "/home/ebcl/.ssh/known_hosts" -R "[localhost]:2222"
      - ssh -p 2222 root@localhost
