version: '3'

tasks:
  run-qemu-efi-amd64:
    cmds:
      - echo "Running {{.result_folder}}/{{.disc_image}} in QEMU x86_64 using EFI loader..."
      - qemu-system-x86_64 -m 4096 -nographic -netdev user,id=mynet0$(qemu_net_append) -device virtio-net-pci,netdev=mynet0 --bios /usr/share/ovmf/OVMF.fd -drive format=raw,file={{.result_folder}}/{{.efi_image}},if=virtio

    sources:
      - '{{.result_folder}}/{{.efi_image}}'