version: '3'

tasks:
  build-root-filesystem-tarball:
    cmds:
      - mkdir -p {{.result_folder}}
      - set -o pipefail && root_generator --no-config {{.root_filesystem_spec}} {{.result_folder}} 2>&1 | tee {{.result_folder}}/{{.base_tarball}}.log

    sources:
      - '{{.root_filesystem_spec}}'
      - '{{.base_spec}}'

    generates:
      - '{{.result_folder}}/{{.base_tarball}}'

  config-root-filesystem-tarball:
    cmds:
      - echo "Configuring {{.base_tarball}} as {{.root_tarball}}..."
      - mkdir -p {{.result_folder}}
      - set -o pipefail && root_configurator {{.root_filesystem_spec}} {{.result_folder}}/{{.base_tarball}} {{.result_folder}}/{{.root_tarball}} 2>&1 | tee {{.result_folder}}/{{.root_tarball}}.log

    sources:
      - '{{.root_filesystem_spec}}'
      - '{{.root_overlay}}'
      - '{{.root_config_script}}'
      - '{{.result_folder}}/{{.base_tarball}}'
      - '{{.result_folder}}/{{.initrd_img}}'
      - '{{.base_spec}}'

    generates:
      - '{{.result_folder}}/{{.root_tarball}}'
