# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  arch: 'aarch64'
  kernel_cmdline_append: "rw"

includes:
  gen: '{{.common_tasks}}Generic.yml'
  sysroot: '{{.common_tasks}}Sysroot.yml'
  qemu_image: '{{.common_tasks}}QEMU_image.yml'
  qemu: '{{.common_tasks}}QEMU.yml'

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:   
      - task: qemu_image:build
      - task: qemu:run_arm64
    method: none

  build:
    desc: Build the image.
    cmds:   
      - task: qemu_image:build
    method: none
