#!/bin/bash

# copy image to tmp
source prepare_image_build $@

# run berrymill
sudo -E env PATH=$PATH berrymill -c $BERRYMILL_CFG -d -a amd64 -i $APPLIANCE --clean build --target-dir /tmp/result_image

set -e
check_image_build
