kernel: linux-image-unsigned-5.15.0-1042-s32-eb-optimized
# CPU architecture
arch: arm64
# Add the EB corbos Linux apt repo
use_ebcl_apt: true
# Add repo with NXP RDB2 packages
apt_repos:
  - apt_repo: https://linux.elektrobit.com/eb-corbos-linux/v1.6.0
    distro: ebcl_nxp_public
    components:
      - nxp_public
    key: file:///build/keys/elektrobit.pub
