# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  arch: 'aarch64'
  partition_layout: ../image.yaml
  initrd_spec: ../initrd.yaml
  boot_spec: ../boot.yaml
  qemu_net_append: ",ipv6-net=fd00::eb/64,ipv6-host=fd00::eb:1,ipv6-dns=fd00::eb:3,hostfwd=tcp::2222-:22,hostfwd=tcp::3333-:3333"
  kernel_cmdline_append: "rw"

includes:
  gen:
    taskfile: '{{.common_tasks}}Generic.yml'
    flatten: true
  sysroot: '{{.common_tasks}}Sysroot.yml'
  qemu_image: '{{.common_tasks}}QEMU_image.yml'
  qemu: '{{.common_tasks}}QEMU.yml'

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:
      - task: qemu_image:build
      - task: qemu:run_arm64
    method: none

  build:
    desc: Build the image.
    cmds:   
      - task: qemu_image:build
    method: none
