# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  kernel_cmdline_append: "rw"
  result_folder: '{{.result_folder | default "./build/"}}'
  qemu_net_append: '{{.qemu_net_append | default ""}}'
  efi_image: '{{.efi_image | default "image.raw"}}'

includes:
  gen:
    taskfile: '{{.common_tasks}}Generic.yml'
    flatten: true
  root: '{{.common_tasks}}RootGenerator.yml'
  embdgen: '{{.common_tasks}}Embdgen.yml'
  qemu: '{{.common_tasks}}QEMU.yml'

tasks:
  default:
    aliases: [build]
    desc: Build the Dom0 QEMU image
    cmds:
      # Prepare root filesystem
      - task: root:build
      - task: root:config
      # Generate Dom0 image
      - task: embdgen:build
      - ./run_grub_install.sh
    method: none

  run_qemu:
    desc: Run the Dom0 image in QEMU
    vars:
      qemu_net_append: '{{.qemu_net_append | default ""}}'
      efi_image: '{{.efi_image | default "image.raw"}}'
    cmds:
      - task: qemu:run_amd64_efi
        vars:
          efi_image: '{{.efi_image}}'
          memory: '8192'
    method: none
