#!/bin/bash

# copy image to tmp
source prepare_image_build $@

# run berrymill
berrymill -c $BERRYMILL_CFG -d -a arm64 -i $APPLIANCE --clean build --cross --box-memory 4G --target-dir /tmp/result_image

set -e
check_image_build
