#!/bin/bash

# copy image to tmp
source /build/scripts/prepare_image_build.sh $@

# run berrymill
berrymill -c $berrymill_config -d -a arm64 -i $appliance_file --clean build --cross --box-memory 4G --target-dir /tmp/result_image

set -e
check_image_build.sh
