#!/bin/bash

# copy image to tmp
source /build/scripts/prepare_image_build.sh $@

# run berrymill
sudo -E env PATH=$PATH berrymill -c $berrymill_config -d -a amd64 -i $appliance_file --clean build --target-dir /tmp/result_image

set -e
check_image_build.sh
