# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  arch: 'aarch64'
  partition_layout: ../image.yaml
  initrd_spec: ../initrd.yaml
  boot_spec: ../boot.yaml
  kernel_cmdline_append: "rw"

includes:
  gen:
    taskfile: '{{.common_tasks}}Generic.yml'
    flatten: true
  sysroot: '{{.common_tasks}}Sysroot.yml'
  qemu_image: '{{.common_tasks}}QEMU_image.yml'
  qemu: '{{.common_tasks}}QEMU.yml'
  test: '{{.common_tasks}}TestExtensions.yml'

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:   
      - task: qemu_image:build
      - task: qemu:run_arm64
    method: none

  build:
    desc: Build the image.
    cmds:   
      - task: qemu_image:build
    method: none
  
  build_performance_test:
    desc: Build the image used by the performance test.
    cmds:
      - task: qemu_image:build
      - task: test:build_test_overlay
        vars:
          test_modifications: performance/
          test_overlay: performance.squashfs
    method: none
  
  run_performance_test:
    desc: Run the performance test variant of the image.
    cmds:
      - task: build_performance_test
      - task: qemu:run_arm64_test
    method: none
  
  build_performance_test_systemd:
    desc: Build the image used by the performance test.
    cmds:
      - task: qemu_image:build
      - task: test:build_test_overlay
        vars:
          test_modifications: performance_systemd/
          test_overlay: performance_systemd.squashfs
    method: none
  

  run_performance_test_systemd:
    desc: Run the performance test variant of the image.
    cmds:
      - task: build_performance_test_systemd
      - task: qemu:run_arm64_test
        vars:
          test_overlay: performance_systemd.squashfs
    method: none
