version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  arch: 'x86_64'
  partition_layout: ../image.yaml
  initrd_spec: ../initrd.yaml
  boot_spec: ../boot.yaml
  qemu_net_append: ",ipv6-net=fd00::eb/64,ipv6-host=fd00::eb:1,ipv6-dns=fd00::eb:3,hostfwd=tcp::2222-:22,hostfwd=tcp::3333-:3333"
  kernel_cmdline_append: "rw"

includes:
  gen: '{{.common_tasks}}Generic.yml'
  root: '{{.common_tasks}}RootGenerator.yml'
  boot: '{{.common_tasks}}BootGenerator.yml'
  initrd: '{{.common_tasks}}InitrdGenerator.yml'
  embdgen: '{{.common_tasks}}Embdgen.yml'
  sysroot: '{{.common_tasks}}Sysroot.yml'
  qemu: '{{.common_tasks}}QEMU.yml'

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:   
      - task: boot:extract_kernel
      - task: root:build
      - task: root:config
      - task: initrd:build
      - task: embdgen:build_qemu
      - task: qemu:run_amd64
    method: none
