#!/bin/bash

# Ensure env is up-to-date
source /workspace/identity/env
GNUPGHOME="/workspace/gpg-keys/.gnupg"
export GNUPGHOME

# prepare folder if not exists
mkdir -p $GNUPGHOME
chmod -R 700 $GNUPGHOME

# generate gnupg script
mkdir -p /workspace/gpg-keys
cp /build/bin/gen_key_script /workspace/gpg-keys/
sed -i "s/DEBFULLNAME/${DEBFULLNAME}/g" /workspace/gpg-keys/gen_key_script
sed -i "s/DEBEMAIL/${DEBEMAIL}/g" /workspace/gpg-keys/gen_key_script

# test if key already exists
gpg --list-secret-keys $DEBEMAIL
# get appliance name
if [ $? -ne 0 ]; then
    gpg --batch --gen-key /workspace/gpg-keys/gen_key_script
fi

gpg --list-keys
gpg --list-secret-keys

sudo chown -R ebcl:ebcl $GNUPGHOME
sudo chmod -R 700 $GNUPGHOME
