#!/bin/bash

echo "Setting EBcL container up..."

# Generate VS Code build tasks
echo "Update VS Code build tasks..."
source /build/venv/bin/activate
python /workspace/tools/tasks/generate_tasks.py

# Install EBcL tools
echo "Install EBcL tools..."
pip install -e /workspace/tools/build

# Add Fakeroot to Python library path
# Hack to make mypy, pylint, ... work for robot libs
ln -s /workspace/tools/build/robot_tests/lib/Fakeroot.py /build/venv/lib/python3.10/site-packages
