#!/bin/bash

echo "Setting EBcL container up..."

# Generate VS Code build tasks
echo "Update VS Code build tasks..."
source /build/venv/bin/activate
python /workspace/tools/tasks/generate_tasks.py

# Install EBcL tools
echo "Install EBcL tools..."
pip install -e /workspace/tools/build
