#!/bin/bash

# Install extensions
extensions="ms-vscode.makefile-tools ms-vscode.cpptools-extension-pack ms-python.python robocorp.robotframework-lsp ms-python.autopep8 ms-python.pylint ms-python.mypy-type-checker WolfiesHorizon.python-auto-venv donjayamanne.python-environment-manager Gruntfuggly.todo-tree"

for ext in $extensions; do
    echo "Installing extension ${ext}..."
    code --install-extension $ext
done

code --list-extensions

# Replace settings
rm -f ../.vscode/settings.json
cp my_settings.json ../.vscode/settings.json
