# Kernel package to use
kernel: linux-image-generic
# CPU architecture
arch: 'amd64'
# Add EBcL apt repository
use_ebcl_apt: true

# Apt repositories to use
apt_repos:
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: noble
    components:
      - main
      - universe
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: noble-security
    components:
      - main
      - universe
