version: '3'

vars:
  result_folder: ./build
  root_filesystem_spec: root.yaml
  base_tarball: ebcl.tar
  config_root_script: config_root.sh
  root_tarball: ebcl.config.tar
  partition_layout: image.yaml
  disc_image: image.raw
  efi_image: image.efi.raw
  grub_config: grub.cfg
  initrd_spec: initrd.yaml
  initrd_img: initrd.img

includes:
  Generic: tasks/Generic.yml
  RootGenerator: tasks/RootGenerator.yml
  InitrdGenerator: tasks/InitrdGenerator.yml
  Embdgen: tasks/Embdgen.yml
  Efi: tasks/Efi.yml
  Qemu: tasks/Qemu.yml


tasks:
  default:
    cmds:
      - task: InitrdGenerator:build-initrd-img
      - task: RootGenerator:build-root-filesystem-tarball
      - task: RootGenerator:config-root-filesystem-tarball
      - task: Embdgen:build-image
      - task: Efi:install-grub
      - task: Qemu:run-qemu-efi-amd64
