# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  common_tasks: /workspace/images/tasks/
  arch: 'x86_64'
  kernel_cmdline_append: "rw"

includes:
  gen:
    taskfile: '{{.common_tasks}}Generic.yml'
    flatten: true
  sysroot: '{{.common_tasks}}Sysroot.yml'
  qemu_image: '{{.common_tasks}}QEMU_image.yml'
  qemu: '{{.common_tasks}}QEMU.yml'

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    cmds:   
      - task: qemu_image:build_efi
      - task: qemu:run_amd64_efi
    method: none
