version: '3'

vars:
  result_folder: ./build
  root_filesystem_spec: root.yaml
  base_tarball: ebcl.tar
  config_root_script: config_root.sh
  root_tarball: ebcl.config.tar
  partition_layout: image.yaml
  disc_image: image.raw
  grub_config: grub.cfg
  initrd_spec: initrd.yaml
  initrd_img: initrd.img

includes:
  Generic: tasks/Generic.yml
  RootGenerator: tasks/RootGenerator.yml
  InitrdGenerator: tasks/InitrdGenerator.yml
  Embdgen: tasks/Embdgen.yml
  Efi: tasks/Efi.yml
  Qemu: tasks/Qemu.yml


tasks:
  default:
    deps:
      - task: Qemu:run-qemu-efi-amd64
