version: '3'

vars:
  arch: 'aarch64'
  partition_layout: ../image.yaml
  root_filesystem_spec: root.yaml
  initrd_spec: initrd.yaml
  boot_spec: boot.yaml
  boot_root_spec: ../boot_root.yaml
  config_root: ../config_root.sh
  base_tarball: build/ebcl_rdb2.tar
  root_tarball: build/ebcl_rdb2.config.tar
  sysroot_tarball: build/ebcl_rdb2_sysroot.tar
  build_fitimage: ../build_fitimage.sh
  fitimage_config: ../bootargs.its
  bootloader_config: ../bootargs-overlay.dts
  fitimage: ./build/fitimage

includes:
  nxp:
    taskfile:  ../../../nxp/rdb2/rdb2.yml
    flatten: true

tasks:
  default:
    desc: Build raspberry NXP RDB2 image
    cmds:
      - task:  build_initrd
      - task:  build_boot_root
      - task:  build_boot
      - task:  build_root_base
      - task:  build_rootfs
      - task:  build_image
