#!/bin/bash 

# add scripts to path
export PATH="/workspace/tools/bin:/build/bin:$PATH"

echo "SDK version $(cat /etc/sdk_version)"

# set GPG home
if [ -d "/workspace/gpg-keys/.gnupg" ]; then
    echo "Setting GPG home..."
    export GNUPGHOME="/workspace/gpg-keys/.gnupg"
fi

# add workspace bin folder if it exists
WSBIN="/workspace/bin"
if [ -d "$WSBIN" ]; then
    echo "Adding '/build/workspace/bin' to PATH..."    
    export PATH="/build/workspace/bin:$PATH"
fi

# source identity if it exists
IDENTITY="/build/identity/env"
if [ -f "$IDENTITY" ]; then
    echo "Sourcing '${IDENTITY}'..."    
    source $IDENTITY
else
    IDENTITY="/workspace/identity/env"
    if [ -f "$IDENTITY" ]; then
        echo "Sourcing '${IDENTITY}'..."    
        source $IDENTITY
    fi
fi

if [ ! -d "/tmp/build/images" ]; then
    bash -c "overlay_mount /build/images"
fi

source /build/venv/bin/activate
