# Makefile for NXP RDB2 systemd variant

#---------------------
# Image specifications
#---------------------

# Specificaiton of the partition layout of the image.raw
partition_layout = image.yaml
# Specificaiton of the initrd.img
initrd_spec = initrd.yaml
# Specificaiton of the root filesystem content and configuration
root_filesystem_spec = root.yaml

#-------------------------
# Additional configuration
#-------------------------

include ../raspberry.mk
