version: '3'

vars:
  arch: 'x86_64'
  partition_layout: ../image.yaml
  root_filesystem_spec: root.yaml
  initrd_spec: ../initrd.yaml
  boot_spec: ../boot.yaml
  config_root: config_root.sh
  base_tarball: build/ebcl.tar
  root_tarball: build/ebcl.config.tar
  sysroot_tarball: build/ebcl_sysroot.tar
  qemu_net_append: ",hostfwd=tcp::2223-:22"

includes:
  qemu_x86_64:
    taskfile: ../../../../qemu_x86_64.yml
    flatten: true
  qemu: 
    taskfile: ../../../../qemu.yml
    flatten: true

tasks:
  default:
    aliases: [run_qemu]
    desc: Build and run the qemu image
    deps: [build_image, build_boot, build_initrd]
    cmds:
      - task: run_qemu_internal
  ssh:
    desc: Build and run the qemu image
    cmds:
      - ssh-keygen -f "/home/ebcl/.ssh/known_hosts" -R "[localhost]:2223"
      - ssh -p 2223 root@localhost
