name: Robot Test images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  import-sdk-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Import and cache sdk image 
      run: |
        CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "linux.elektrobit.com" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')
        docker manifest inspect ghcr.io/elektrobit/sdk:$CONTAINER_TAG && exit 0 || true
        ./init_workspace
        docker tag linux.elektrobit.com/ebcl/sdk:$CONTAINER_TAG ghcr.io/elektrobit/sdk:$CONTAINER_TAG
        docker push ghcr.io/elektrobit/sdk:$CONTAINER_TAG

  test:
    runs-on: ubuntu-latest
    needs: import-sdk-image
    strategy:
      fail-fast: false
      matrix:
        test_case:
          # Add an entry for each Robot Framework test case you want to run separately.
          # Each entry will call a specific test case by name.
          - "Build Image amd64/qemu/jammy/berrymill"
          - "Build Image amd64/qemu/jammy/debootstrap"
          - "Build Image amd64/qemu/jammy/kiwi"
          - "Build Image amd64/qemu/ebcl/systemd/berrymill"
          - "Build Image amd64/qemu/ebcl/systemd/debootstrap"
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-venv python-is-python3 binfmt-support qemu-user-static
      - uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Import cached sdk image 
        run: |
          CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "linux.elektrobit.com" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')
          docker pull ghcr.io/elektrobit/sdk:$CONTAINER_TAG && docker tag ghcr.io/elektrobit/sdk:$CONTAINER_TAG linux.elektrobit.com/ebcl/sdk:$CONTAINER_TAG
          
      - name: Run Robot Test in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            robot --outputdir ./robot_tests --test "${{ matrix.test_case }}" ./robot_tests/images.robot
      
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: "report-${{ matrix.test_case }}"
          path: ./robot_tests/report.html
