name: Test .vscode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  import-sdk-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Import and cache sdk image 
      run: |
        CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "linux.elektrobit.com" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')
        docker manifest inspect ghcr.io/elektrobit/sdk:$CONTAINER_TAG && exit 0 || true
        ./init_workspace
        docker tag linux.elektrobit.com/ebcl/sdk:$CONTAINER_TAG ghcr.io/elektrobit/sdk:$CONTAINER_TAG
        docker push ghcr.io/elektrobit/sdk:$CONTAINER_TAG

  task:
    runs-on: ubuntu-latest
    needs: import-sdk-image
    strategy:
      fail-fast: false
      matrix:
        task:
          - "EBcL: Image amd64/appdev/qemu/crinit"
          - "EBcL: Image amd64/qemu/ebcl/crinit/debootstrap"
          - "EBcL: Image arm64/appdev/qemu/crinit"
          - "EBcL: Image arm64/appdev/rdb2/crinit"
          - "EBcL: Image arm64/nxp/rdb2/crinit"
          - "EBcL: Image arm64/qemu/ebcl/crinit/debootstrap"
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-venv python-is-python3 binfmt-support qemu-user-static
      - uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Import cached sdk image 
        run: |
          CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "linux.elektrobit.com" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')
          docker pull ghcr.io/elektrobit/sdk:$CONTAINER_TAG && docker tag ghcr.io/elektrobit/sdk:$CONTAINER_TAG linux.elektrobit.com/ebcl/sdk:$CONTAINER_TAG
          
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            sudo pip install vscode-task-runner==1.3.3
            vtr "${{ matrix.task }}"
