name: Test .vscode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.tasks.outputs.tasks }}
    steps:
      - uses: actions/checkout@v4
      - name: Run devcontainer once to generate tasks
        uses: devcontainers/ci@v0.3
      - name: Scan tasks
        id: tasks
        run: |
          echo "tasks=$(jq '.tasks[].label' .vscode/tasks.json | grep -E '(Sysroot|Image)')" >> $GITHUB_OUTPUT
    
  task:
    runs-on: ubuntu-latest
    needs: discover
    strategy:
      fail-fast: false
      matrix:
        task:
          ${{ fromJson(needs.discover.outputs.tasks) }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-venv python-is-python3 binfmt-support qemu-user-static
          
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            sudo pip install vscode-task-runner==1.3.3
            vtr "${{ matrix.task }}"
