name: Test .vscode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  task:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - "EBcL: Image amd64/appdev/qemu/crinit"
          - "EBcL: Image amd64/qemu/ebcl/crinit/debootstrap"
          - "EBcL: Image arm64/appdev/qemu/crinit"
          - "EBcL: Image arm64/appdev/rdb2/crinit"
          - "EBcL: Image arm64/nxp/rdb2/crinit"
          - "EBcL: Image arm64/qemu/ebcl/crinit/debootstrap"
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-venv python-is-python3 binfmt-support qemu-user-static
          
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            sudo pip install vscode-task-runner==1.3.3
            vtr "${{ matrix.task }}"
